image:
  file: .gitpod.Dockerfile

tasks:
  - name: Flutter Setup
    init: |
      flutter doctor
      flutter pub get
    command: |
      echo "Środowisko Flutter gotowe!"
      echo "Wpisz 'flutter run' aby uruchomić aplikację."

ports:
  - port: 6080
    onOpen: open-preview
